ignore-embedded-fields: true

ignore-symbols:
  - kinds:
      - Method
    names:
      - "*Scan"
      - "*Value"
      - "*UnmarshalJSON"
      - "*MarshalJSON"
      - "*String"

  - kinds:
      - Function
    names: ["init", "main"]
